@startuml

left to right direction
actor 視聴者
rectangle テレビアプリ{
	視聴者 --> (視聴する)
	視聴者 --> (チャンネル選択)
	視聴者 --> (音量調節)
	視聴者 --> (画質調節)
	視聴者 --> (録画)
}

actor ユーザ
actor 管理者s
rectangle ショッピングサイト{
	ユーザ --> (閲覧)
	ユーザ --> (検索)
	ユーザ --> (購入)
	ユーザ --> (返品)
	ユーザ --> (問い合わせ)
	ユーザ --> (ログイン)
	(ログイン) <-- 管理者s
	(注文確認) <-- 管理者s
	(商品管理) <-- 管理者s
	(問い合わせを応対) <-- 管理者s
}
(商品発送) <-- 管理者s

@enduml